language: python
python:
    - "3.6"

before_script:
  - cd homeworks/homework_09_web
  - docker build -t myapp .
  - docker run --name myapp -d myapp

script: docker exec myapp python -m pytest --pep8 && python -m pytest --cov=.