language: python
python:
    - "3.6"

services:
  - docker

before_script:
  - cd homeworks/homework_09_web
  - docker build -t myapp .
  - docker run --name myapp -d myapp

script: docker exec -it myapp /bin/sh -c 'cd myapp && sleep 5 && python -m pytest --pep8 && python -m pytest --cov=.'

after_script:cvfv
  - docker rm -f myapp