# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-10 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aircraft',
            table='aircraft',
        ),
        migrations.AlterModelTable(
            name='airflight',
            table='airflight',
        ),
        migrations.AlterModelTable(
            name='airport',
            table='airport',
        ),
    ]
